package com.oolshik.backend.domain;

public enum HelpRequestEventType {
    ACCEPTED,
    AUTH_REQUESTED,
    AUTH_APPROVED,
    AUTH_REJECTED,
    AUTH_TIMEOUT,
    RELEASED,
    REASSIGNED,
    CANCELLED,
    TIMEOUT,
    COMPLETED,
    WORK_MARKED_DONE,
    COMPLETION_CONFIRMED,
    COMPLETION_ISSUE_REPORTED,
    AUTO_COMPLETED_BY_TIMEOUT,
    RADIUS_EXPANDED,
    CREATE_BLOCKED_CAP_REACHED
}
